config/routes.rb
Reservester2::Application.routes.draw do
  devise_for :owners
  resources :restaurants

  root 'restaurants#index'

end

app/models/owner.rb
class Owner < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find_by_id(params[:id])
  end

  def new
    @restaurant = Restaurant.new(params[:restaurant])
  end

  def create
    @restaurant = Restaurant.create(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant 
    else
      render 'new'
    end    
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update_attributes(restaurant_params)
      redirect_to @restaurant 
    else
      render 'edit'
    end
  end

  def destroy
    restaurant = Restaurant.find(params[:id])
    restaurant.destroy
    redirect_to restaurants_path
  end

  private

    def restaurant_params
      params.require(:restaurant).permit(:name, :desc, :address, :phone, :image, :remote_image_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reservester2</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="owner_nav">
  <% if owner_signed_in? %>
    Signed in as <%= current_owner.email %>. Not you?
    <%= link_to "Sign out", destroy_owner_session_path, :method => :delete %>
  <% else %>
    <%= link_to "Sign up", new_owner_registration_path %> or <%= link_to "sign in", new_owner_session_path %>
  <% end %>
</div>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant, :html => {:multipart => true} do |f| %>


<div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
   <div class="field">
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit Restaurant</h1>

<%= render 'form' %>

app/views/restaurants/index.html.erb
<h1>Reservester</h1>
<% @restaurants.each do |x| %>
<p><%= link_to "#{x.name}", x %></p>
<%= image_tag "#{x.image_url(:thumb)}" %>
	<% end %>

<br>
<hr>

<%= link_to("New Restaurant", new_restaurant_path) %> 
<%= link_to "Back", root_path %>

<p></p>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>

<%= render 'form' %>

app/views/restaurants/show.html.erb
<h1><%= "#{@restaurant.name}" %></h1>
<%= image_tag @restaurant.image_url(:masthead) %>




<%= link_to 'Edit', edit_restaurant_path %>
<%= link_to 'Destroy', restaurant_path, method: :delete, data: { confirm: 'Are you sure?'} %>